### ISSUE TITLE
Is it possible to allow '~/' in path?

### ISSUE THREAD

**Issue by zizther** [sindresorhus/path-exists#1]
I am looking to use '~/.docker/config.json' as the file path but it does not work. If i use an absolute path it works fine.
At the moment I am using $HOME in a shell.exec function, which feels a bit messy. Unless this is the right way.

What is the best way to handle using '~' in the path, or will this never be possible?

**Comment by vyp** [comment]
I think https://github.com/nodejs/node/issues/684 is the relevant issue to reference. And do remember that the tilde is just a shell feature (in bash, zsh etc).

**Comment by sindresorhus** [comment]
This should really be in Node.js core, but they seem unwilling: https://github.com/nodejs/node/issues/684

You can use https://github.com/sindresorhus/untildify to expand the tilde.
