### ISSUE TITLE
Check if the file is a regular file, directory, etc.

### ISSUE THREAD

**Issue by ehmicky** [sindresorhus/path-exists#13]
It would be good to allow checking the file type as well (regular file, directory, etc.).

This would require using `fs.stat()` instead of `fs.access()`.

This could be implemented either as a different exported method or as an option.

**Comment by sindresorhus** [comment]
> This could be implemented either as a different exported method or as an option.

Which would you prefer?

**Comment by ehmicky** [comment]
I think using a different exported method might be closer to functional programming. 

On the other hand, it would also require a breaking change (named export vs default export) and might make the interface more complicated. So based on this, I would say an option object, although I don't have a strong preference for either direction. 

When it comes to the file type, this could be either:
  - a boolean (is regular file or is directory) which would always be `false` for special file types
  - a string enum which could include or not special file types

Please let me know what you think.

**Comment by sindresorhus** [comment]
Hmm, I just remembered. I already have a module for this: https://github.com/sindresorhus/path-type

**Comment by ehmicky** [comment]
I was surprised you did not already! Great, problem fixed!
