### ISSUE TITLE
Only file and data URLs are supported by the default ESM loader.

### ISSUE THREAD

**Issue by budiga** [sindresorhus/path-exists#17]
`function checkUserHome() {
  const p = import('path-exists')
  p.then(rst => {
    console.log('----- rst -----', rst)
  }, e => {
    console.log('----- e -----', e)
  })
}
checkUserHome()`

When I run this code in Node, it will throw a error:[ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader.

How can I avoid this error?
node version: v12.18.3
npm version: 6.14.6

**Comment by sindresorhus** [comment]
This is not a problem with this package.
