### ISSUE TITLE
check if file exists case-sensitive

### ISSUE THREAD

**Issue by andyqier88** [sindresorhus/path-exists#19]
when i use like below, the results are true
```
import { pathExists } from 'path-exists';

console.log(await pathExists('./readme.md')); // true
console.log(await pathExists('./README.md')); // true
```
in my `boundary-judgment`  [fileExistsWithCaseSync](https://github.com/andyqier88/boundary-judgment/tree/main/lib/fileExistsWithCaseSync) based on [check-if-file-exists-case-sensitive](https://stackoverflow.com/questions/27367261/check-if-file-exists-case-sensitive)

**Comment by sindresorhus** [comment]
If the file system is case-insensitive, the above behavior is correct. I don't think this package should work around that. Even a valid need for this is quite niche, so I'm going to pass on adding an option for it.
