### ISSUE TITLE
Example is not completely clear

### ISSUE THREAD

**Issue by hkirsman** [sindresorhus/path-exists#2]
I think it would help if there would be if clause in the example. Because I would assume from "pathExists('foo').then  that it already has done the check. But instead this is correct:

```
// foo.js 
var pathExists = require('path-exists');

pathExists('foo.js').then(function (exists) {
    if (exists) {
        console.log('foo.js exists');
    }
});
```

**Comment by sindresorhus** [comment]
Thanks for you input, but I honestly feel the example is more than clear enough. It's even clearly spelled out in the API docs:

> Returns a promise that resolves to a **boolean of whether the path exists.**
