### ISSUE TITLE
Remove 'const' usage

### ISSUE THREAD

**Issue by blissland** [sindresorhus/path-exists#5]
Please can you reconsider using the 'const' syntax ie

`const fs = require('fs');`

This syntax does not run by default in older versions of node. See here:

http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode

**Comment by SamVerschueren** [comment]
Why not upgrade node? If not possible, use an older version.

**Comment by blissland** [comment]
Currently not possible to upgrade node.js for various reasons on my platform (raspberry pi). 

You module is included (indirectly) by the Peerflix module:

https://github.com/mafintosh/peerflix/

So users currently doing "npm install peerflix" and then attempting to run it on old versions of node will fail because of the 'const' syntax

**Comment by sindresorhus** [comment]
Then stay on the old version of `path-exists`. Node.js 0.10 and 0.12 are out of active LTS.

**Comment by SamVerschueren** [comment]
I'm not sure but it might be possible to use schrinkwrap to solve that issue.

**Comment by blissland** [comment]
I will try to get the author of the module that includes yours to use the old version.

**Comment by feross** [comment]
I understand the desire to stop supporting old node. I've been encouraging people to stop using node 0.10 and 0.12 since all support (including security) will cease at the end of the year.

However, I personally stop short of intentionally dropping 0.10/0.12 support from packages that used to support it unless there's a really good reason. "I like how this new code looks" isn't a good enough reason in my opinion. Curious what the rationale was.

**Comment by sindresorhus** [comment]
It was done to remove a [dependency](https://github.com/sindresorhus/path-exists/pull/4/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L34). The module already didn't support Node.js 0.10 btw. I'm trying to slim down my dependency tree, as a [large part of it are polyfills](https://github.com/yargs/yargs/issues/449#issuecomment-201738097) for older Node.js versions. This was done in a major release and the module is pretty much done, so I don't really see a problem with it. Just stay on the older version if you really need to be compatible with unsupported Node.js versions. I don't think it's fair to require a module to wait until every single user has upgraded.
