### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by alextes** [sindresorhus/path-exists#8]
Was helping a newbie write file exists logic using `fs.access`. It just became too much for him explaining err-first-callbacks, plus `async.parallel`, plus binding functions, plus having to turn the `fs.access` error into a boolean. This makes everything so much easier. Was worried you wouldn't have a package, but of course, you do 😄 .

Thanks from me and bohdan.birdie! 
(you can close this)

**Comment by sindresorhus** [comment]
It's such a small and simple package. Glad it could have some positive impact 😃
